# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# .github/workflows/deploy.yml
name: FastAPI Azure Deployment

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: prasanth-fastapi-app
  RESOURCE_GROUP: fastapi-rg

jobs:

  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App (staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: staging
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .

  approval-before-swap:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Waiting for approval
        run: echo "Waiting for production approval"

  swap-to-production:
    needs: approval-before-swap
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap staging slot to production
        run: |
          az webapp deployment slot swap \
            --resource-group $RESOURCE_GROUP \
            --name $AZURE_WEBAPP_NAME \
            --slot staging \
            --target-slot production
