# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy FastAPI to Azure

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: py-fastapi-prod
  RESOURCE_GROUP: fastapi-py1

jobs:

  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: staging
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_69F45359EEF6447D97A74D6FA8CCEFAC }}
          package: .

  swap-to-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Swap staging slot to production
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deployment slot swap \
              --name py-fastapi-prod \
              --resource-group fastapi-py1 \
              --slot staging \
              --target-slot production

